Desktop/D_project/helpdesk/help/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'help'

urlpatterns = [
    # отображение поста
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

Desktop/D_project/helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from help.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('help/', include('help.urls', namespace='help')),
    path('sitemap.xml', sitemap,{'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

Desktop/D_project/helpdesk/help/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.

# Модель менеджера публикаций

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

# Модель отображения задачи (поста)
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='help_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()  # менеджер по умолчанию
    published = PublishedManager()
    tags = TaggableManager()

# Публикация последних постов(задач) от последних к первым
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('help:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug,
                             ])

# Модель системы комментариев

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

# Модель системы теггирования

#class Tag(models.Model):



    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Коментарий {self.name} на {self.post}'

Desktop/D_project/helpdesk/help/forms.py
from django import forms
from .models import Comment

# Форма для отправки сообщения на email

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

# Форма для отправки комментария

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

# Форма поиска

class SearchForm(forms.Form):
    query = forms.CharField()

Desktop/D_project/helpdesk/help/views.py
from django.shortcuts import render, get_object_or_404
#from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from .models import Post, Comment
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count

# Create your views here.
# Cтраница отображения списка заявок(постов)
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Постраничная разбивка с отображением 5 задач на странице
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Если номер страницы не целое число, то выдаем 1 страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если страница находитсяя вне диапазона, то выдать последнюю страницу
        posts = paginator.page(paginator.num_pages)

    return render(request, 'help/post/list.html', {'posts': posts,
                                                   'tag': tag,})

# Формирование ссылки поста (ссылка отображает дату создания поста и слаг), отображение полного содержания заявки
def post_detail(request, year, month, day, post):

    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             )
    # Список активных комментариев к этому посту
    comments = post.comments.filter(active=True)
    # Форма для комментариев пользователями
    form = CommentForm()

    #Список схожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                   .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                   .order_by('-same_tags','-publish')[:4]

    return render(request, 'help/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'form': form,
                                                     'similar_posts': similar_posts
                                                     })

# Forms EMAIL

def post_share(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)

    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} рекомендует прочесть " f"{  post.title }"
            message = f"Прочти {post.title} по {post_url}\n\n" f"{cd['name']} комментарий: {cd['comments']}"
            send_mail(subject, message, 'a09@yandex.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'help/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

# Модель формы комментариев
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в базе данных
        comment.save()
    return render(request, 'help/post/comment.html', {'post': post,
                                                      'form': form,
                                                      'comment': comment})

# Модель формы поиска

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            #search_vector = SearchVector('title', 'body', config='russian')
            #search_query = SearchQuery(query, config='russian')
            results = Post.published.annotate(
                similarity = TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
               # search=search_vector,
               # rank=SearchRank(search_vector, search_query)
            #).filter(search=search_query).order_by('-rank')

    return render(request,
                  'help/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results
                   })

Desktop/D_project/helpdesk/help/templates/help/post/comment.html
{% extends "help/base.html" %}

{% block title %} Добавить комментарий {% endblock %}

{% block content %}
    {% if comment %}
        <h2>
            Ваш комментарий был добавлен
        </h2>
        <p>
            <a href="{{ post.get_absolute_url }}">
                Вернуться к задаче
            </a>
        </p>
    {% else %}
        {% include "help/post/comment_form.html" %}
    {% endif %}
{% endblock %}

Desktop/D_project/helpdesk/help/templates/help/post/detail.html
{% extends 'help/base.html' %}
{% load help_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1> <p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
    <a href="{% url 'help:post_share' post.id %}">
        Поделиться задачей (отправить на e-mail)
    </a>
</p>

<h2>Похожие посты</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absoluute_url}}">{{ post.title }}</a>
</p>
{% empty %}
    Похожих постов пока нет
{% endfor %}

{% with comments.count as total_comments %}
<h2>
    {{ total_comments}} комментарий(я)
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Комментарий {{ forloop.counter}} от {{ comment.name }}
        {{ comment.created }}
    </p>
    <p>
        <!-- body comment-->
        {{ comment.body|linebreaks }}
    </p>
</div>
{% empty %}
    <p>
        Нет комментариев
    </p>
{% endfor %}

{% include 'help/post/includes/comment_form.html' %}

{% endblock %}

Desktop/D_project/helpdesk/help/templates/help/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

Desktop/D_project/helpdesk/help/templates/help/post/list.html
{% extends 'help/base.html' %}
{% load help_tags %}

{% block title %}HELPDESK{% endblock %}

{% block content %}
<h1>СКОРАЯ ПОМОЩЬ</h1>
{% if tag %}
    <h2>Пост, который содержит тег: "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts%}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{post.title}}
    </a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
        <a href="{% url 'help:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.list %}, {% endif %}
    {% endfor %}
</p>
<p class="date">
    Дата: {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30 }}
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

Desktop/D_project/helpdesk/help/templates/help/post/search.html
{% extends "help/base.html" %}
{% load help_tags %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Задачи, которые содержат "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
            Найдено {{ total_results }} задач {{ total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
        {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
        <p>По вашему запросу ничего не найдено</p>
        {% endfor %}
        <p><a href="{% url 'help:post_search' %}">Искать снова</a></p>
        {% else %}
        <h1>Поиск по задачам</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Найти">
        </form>
    {% endif %}
{% endblock %}

Desktop/D_project/helpdesk/help/templates/help/post/share.html
{% extends "help/base.html" %}

{% block title %} Поделиться задачей {% endblock %}

{% block content %}
{% if sent %}
<h1>Ваше сообщение успешно отправлено</h1>
<p>
    "{{ post.title }}" было успешно отправлено
    на {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Поделиться "{{ post.title }}" на e-mail</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}